fieldLayouts:
  8a8ee694-983c-41b7-b91f-9e8294375d5a:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 08c521cf-a8a6-467e-8ae6-ffcb131478c1
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 97de7b47-515f-4d89-a189-4585140f7564
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Page header'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 12a7f841-74b6-4229-8266-fd7a6d4dd2d8
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: blog
hasTitleField: false
name: Blog
section: 31ad9b5c-ed47-4253-8528-65c2d6286ea5
sortOrder: 1
titleFormat: '{heading}'
