enableVersioning: true
handle: caseStudy
name: Référence
propagationMethod: all
siteSettings:
  d7655a13-1d4e-455c-8ce3-29ab32497ad4:
    enabledByDefault: true
    hasUrls: true
    template: structures/casestudy
    uriFormat: 'referentie/{slug}'
  e3415183-c41b-406f-b496-b97591cc0484:
    enabledByDefault: true
    hasUrls: true
    template: structures/casestudy
    uriFormat: 'référence/{slug}'
structure:
  maxLevels: null
  uid: 3d9155d8-3818-43c1-94ba-f6eb1a288dc3
type: structure
