enableVersioning: true
handle: jobs
name: Jobs
propagationMethod: all
siteSettings:
  d7655a13-1d4e-455c-8ce3-29ab32497ad4:
    enabledByDefault: true
    hasUrls: true
    template: singles/jobs
    uriFormat: job
  e3415183-c41b-406f-b496-b97591cc0484:
    enabledByDefault: true
    hasUrls: true
    template: singles/jobs
    uriFormat: job
type: single
