enableVersioning: true
handle: service
name: Service
propagationMethod: all
siteSettings:
  d7655a13-1d4e-455c-8ce3-29ab32497ad4:
    enabledByDefault: true
    hasUrls: true
    template: structures/service
    uriFormat: 'dienst/{slug}'
  e3415183-c41b-406f-b496-b97591cc0484:
    enabledByDefault: true
    hasUrls: true
    template: structures/service
    uriFormat: 'service/{slug}'
structure:
  maxLevels: null
  uid: 39d60033-adeb-4fb6-a344-47e21d550f7f
type: structure
